python main.py --pi_path PI_data10 --save_model results_10.pt --test
python main.py --pi_path PI_data20 --save_model results_20.pt --test
python main.py --pi_path PI_data30 --save_model results_30.pt --test
python main.py --pi_path PI_data40 --save_model results_40.pt --test
python main.py --pi_path PI_data50 --save_model results_50.pt --test
python main.py --pi_path PI_data60 --save_model results_60.pt --test
python main.py --pi_path PI_data70 --save_model results_70.pt --test
python main.py --pi_path PI_data80 --save_model results_80.pt --test
python main.py --pi_path PI_data90 --save_model results_90.pt --test
python main.py --pi_path PI_data100 --save_model results_100.pt --test